name: numpy.array_api
on: [push]

jobs:
  numpy_array_api_job:
    runs-on: ubuntu-latest
    name: Generate a report for numpy.array_api
    steps:
      - id: run-array-api-tests-reporting-action
        uses: data-apis/array-api-tests-reporting-action@main
        with:
          array-api-tests-module: numpy.array_api
          array-library-version: "TODO"
          array-library-install: |
            python -m pip install numpy
      - name: 'Post data'
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.DATA_APIS_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.DATA_APIS_WEBHOOK_SECRET }}
          data: ${{ steps.run-array-api-tests-reporting-action.outputs.post_data }}
