name: Plain NumPy
on: [push]

jobs:
  numpy_array_api_job:
    runs-on: ubuntu-latest
    name: Generate a report for plain NumPy
    steps:
      - id: run-array-api-tests-reporting-action
        uses: data-apis/array-api-tests-reporting-action@main
        with:
          array-api-tests-module: numpy
          array-library-version: "TODO"
          array-library-install: |
            python -m pip install numpy
